////////////////////////////////////////////////////////////////////////
// Class:       MichelRecoDriver
// Module Type: producer
// File:        MichelRecoDriver_module.cc
//
// David Caratelli - davidc1@fnal.gov - November 14 2016
////////////////////////////////////////////////////////////////////////

#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "canvas/Persistency/Common/FindManyP.h"
#include "canvas/Utilities/InputTag.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"

// services etc...
#include "larcore/Geometry/Geometry.h"
#include "lardata/DetectorInfoServices/DetectorPropertiesService.h"
#include "lardata/DetectorInfoServices/LArPropertiesService.h"

// data-products
#include "lardataobj/RecoBase/Cluster.h"
#include "lardataobj/RecoBase/Hit.h"
//#include "lardata/Utilities/AssociationUtil.h"
#include "art/Persistency/Common/PtrMaker.h"

// C++
#include <memory>
#include <iostream>
#include <utility>

// Michel framework
#include "uboone/MichelReco/Fmwk/MichelRecoManager.h"
#include "uboone/MichelReco/Fmwk/HitPt.h"
#include "uboone/MichelReco/Fmwk/MichelTypes.h"
#include "uboone/MichelReco/Algo/AlgorithmFactory.h"

class MichelRecoDriver;

class MichelRecoDriver : public art::EDProducer {
public:
  explicit MichelRecoDriver(fhicl::ParameterSet const & p);
  // The destructor generated by the compiler is fine for classes
  // without bare pointers or other resource use.

  // Plugins should not be copied or assigned.
  MichelRecoDriver(MichelRecoDriver const &) = delete;
  MichelRecoDriver(MichelRecoDriver &&) = delete;
  MichelRecoDriver & operator = (MichelRecoDriver const &) = delete;
  MichelRecoDriver & operator = (MichelRecoDriver &&) = delete;

  // Required functions.
  void endJob();
  void produce(art::Event & e) override;


private:

  // producer of input clusters to use
  std::string fClusterProducer;

  // producer of reconstructed hits to use as input
  std::string fHitProducer;

  // minimum cluster size
  size_t fMinClusSize;

  // use clusters from this plane (0, 1, 2)
  geo::PlaneID::PlaneID_t fUsePlane;

  // constants used [detector properties]
  double _w2cm, _t2cm;

  // instance of reco manager
  michel::MichelRecoManager* _mgr;

  // functions
  std::vector< ::michel::HitPt > PrepareClusterHits( const std::vector<art::Ptr<recob::Hit> >& hit_v );

};


MichelRecoDriver::MichelRecoDriver(fhicl::ParameterSet const & p)
  : _mgr(nullptr)
    // Initialize member data here.
{
  
  produces< std::vector< recob::Cluster > >("electron");
  produces< std::vector< recob::Cluster > >("photon");
  produces< art::Assns < recob::Cluster, recob::Hit> >("electron");
  produces< art::Assns < recob::Cluster, recob::Hit> >("photon");

  fClusterProducer  = p.get<std::string>("ClusterProducer");
  fHitProducer      = p.get<std::string>("HitProducer");
  fMinClusSize      = p.get<size_t>     ("MinClusSize");
  fUsePlane     = p.get<geo::PlaneID::PlaneID_t>( "UsePlane", 2 ); // default: collection plane

  // get detector specific properties
  auto const* geom = lar::providerFrom<geo::Geometry>();
  auto const* detp = lar::providerFrom<detinfo::DetectorPropertiesService>();
  _w2cm = geom->WirePitch( static_cast<geo::View_t>( fUsePlane ) );
  _t2cm = detp->SamplingRate() / 1000.0 * detp->DriftVelocity( detp->Efield(), detp->Temperature() );

  std::cout << "**********************" << std::endl
	    << "Wire 2 Cm -> " << _w2cm << std::endl
	    << "Time 2 Cm -> " << _t2cm << std::endl
	    << "**********************" << std::endl;

  _mgr = new michel::AlgoDefault();

}

void MichelRecoDriver::endJob()
{
  _mgr->Finalize();
  return;
}

void MichelRecoDriver::produce(art::Event & e)
{

  _mgr->EventReset();



  // produce Cluster data-product to be filled within module
  std::unique_ptr< std::vector<recob::Cluster> > electron_v(new std::vector<recob::Cluster>);
  std::unique_ptr< std::vector<recob::Cluster> > photon_v(new std::vector<recob::Cluster>);
  std::unique_ptr< art::Assns <recob::Cluster, recob::Hit> > elec_clus_hit_assn_v( new art::Assns<recob::Cluster, recob::Hit> );
  std::unique_ptr< art::Assns <recob::Cluster, recob::Hit> > photon_clus_hit_assn_v( new art::Assns<recob::Cluster, recob::Hit> );

  // load hits
  auto input_hit_h = e.getValidHandle< std::vector<recob::Hit> >(fHitProducer);

  // and clusters
  auto input_cluster_h = e.getValidHandle< std::vector<recob::Cluster> >(fClusterProducer);

  // grab hits associated with input clusters
  art::FindManyP<recob::Hit> cluster_hit_assn_v(input_cluster_h, e, fClusterProducer );

  // set event info for manager
  michel::EventID id;
  id.run    = e.run();
  id.subrun = e.subRun();
  id.event  = e.event();
  _mgr->SetEventInfo( id );

  
  std::cout << "Event " << e.event() << "\t Subrun : " << e.subRun() << "\t Run : " << e.run() << std::endl;

  // save all collection-plane hits
  std::vector< ::michel::HitPt > all_hits_v;
  all_hits_v.reserve(input_hit_h->size());

  for(size_t h=0; h < input_hit_h->size(); h++){
    
    auto const& hit = input_hit_h->at(h);

    //int chan = hit.Channel();
    double q = hit.Integral();
    double w = hit.WireID().Wire * _w2cm;
    double t = hit.PeakTime() * _t2cm;
    unsigned int p = hit.WireID().Plane;

    all_hits_v.emplace_back( q , w, t, h, p );
  }

  // all hits vector is registered to the manager for future use (search for local hits not clustered)                                                                  
  std::cout << "registering hits" << std::endl;
  _mgr->RegisterAllHits( std::move(all_hits_v) );
  std::cout << "done" << std::endl;

  // loop through all input clusters
  for (size_t i=0; i < input_cluster_h->size(); i++){
    
    auto const cluster = input_cluster_h->at(i);

    // grab hits associated to this cluster
    //std::vector<const recob::Hit*> hit_v = cluster_hit_assn_v.at(i);
    const std::vector<art::Ptr<recob::Hit> >& hit_v = cluster_hit_assn_v.at(i);

    // if hits not from desired plane -> skip
    if (hit_v.size() == 0) continue;
    if (hit_v.at(0)->WireID().Plane != fUsePlane) continue;

    // prepare hit-list for this cluster
    std::vector< ::michel::HitPt > michel_cluster = PrepareClusterHits(hit_v);

    if (michel_cluster.size() > fMinClusSize)
      _mgr->Append( std::move(michel_cluster), i);
    
  }// for all input clusters
  
  // run the reconstruction!
  _mgr->Process();

  // grab the results
  auto const& michels = _mgr->GetResult(); // vector of michel::MichelClusters

  // cluster ptr maker which will be used to fill associations
  art::PtrMaker<recob::Cluster> makeClusterPtrElectron(e, *this, "electron");
  art::PtrMaker<recob::Cluster> makeClusterPtrPhoton  (e, *this, "photon"  );

  // save the output
  for (auto const& michelClus : michels){

    auto const& michel = michelClus._michel; // michel::Michel object
    
    // if no michel hits -> don't continue saving the cluster
    if ( michel._electron_hit_idx_v.empty() ) continue;

    // create a new cluster for the electron

    // michel::Michel start used for both the electron and the photon(s)
    float start_wire   = michel._start._w / _w2cm; 
    float start_tick   = michel._start._t / _t2cm;
    unsigned int nhits = michel._electron_hit_idx_v.size();
    // Loop over hits from electron cluster to compute this cluster's total charge
    float Qelectron = 0;
    for (auto const& michel_elec_hit_idx : michel._electron_hit_idx_v){
      Qelectron += michel.at( michel_elec_hit_idx )._q;
    }
    std::cout << "Charge from e hits " << Qelectron << std::endl; 
    //std::cout << "Charge from Michel " << michel._charge << std::endl; 

    // Just filling the minimal set of variables
    recob::Cluster electron_clus( start_wire,  // start_wire
				  0.,          // sigma_start_wire
				  start_tick,  // start tick
				  0.,          // sigma_start_tick
				  0.,          // start_charge
				  0.,          // start_angle
				  0.,          // start_opening
				  0.,          // end_wire
				  0.,          // sigma_end_wire
				  0.,          // end_tick
				  0.,          // sigma_end_tick
				  0.,          // end_charge
				  0.,          // end_angle
				  0.,          // end_opening
				  Qelectron,   // integral
				  0.,          // integral_stddev
				  0.,          // summedADC
				  0.,          // summedADC_stddev
				  nhits,       // n_hits
				  0.,          // multiple_hit_density
				  0.,          // width
				  0.,          // ID_t
				  static_cast<geo::View_t>( fUsePlane ), // view
				  geo::PlaneID(0, 0, fUsePlane) );

    electron_v->emplace_back( electron_clus );

    const art::Ptr<recob::Cluster> cluster_ptr = makeClusterPtrElectron( electron_v->size() - 1 );

    // loop through all tagged electron hits, store in vector of Art pointers
    // std::vector< art::Ptr<recob::Hit > > electron_hit_ptr_v;

    for (auto const& michel_elec_hit_idx : michel._electron_hit_idx_v){
      size_t idx = michel.at( michel_elec_hit_idx )._id;
      const art::Ptr<recob::Hit> hit_ptr(input_hit_h, idx);
      elec_clus_hit_assn_v->addSingle( cluster_ptr, hit_ptr);
    }

    // std::cout << "\tSaved new Michel with " << electron_hit_ptr_v.size() << " hits!" << std::endl;

    // grab photon hits
    for (auto const& photon_hit_v : michel._photon_clus_v){

      if ( photon_hit_v.empty() ) continue;
      
      // loop through all tagged photon hits, store in vector of Art pointers
      // std::vector< art::Ptr<recob::Hit > > photon_hit_ptr_v;

      // Loop over hits from photon cluster to compute this cluster's total charge
      float Qphoton =  0;
      for (auto const& photon_hit_idx : photon_hit_v){
	Qphoton += michel[ photon_hit_idx ]._q;
      }
      std::cout << "Charge from g hits " << Qphoton << std::endl; 
      //std::cout << "Charge from Michel " << michel._charge << std::endl; 
      
      // create a new cluster for the photon hits
      recob::Cluster photon_clus( start_wire, 0., start_tick, 0., // start wire/wire stddev/tick/tick stddev
				  0., 0., 0.,                     // start charge/angle/opening
				  0., 0., 0., 0.,                 // end wire/wire stddev/tick/tick stddev
				  0., 0., 0.,                     // end charge/angle/opening
				  Qphoton, 0., 0., 0.,                 // integral, integral stddev, summedADC, summedADC stddev
				  nhits, 0., 0., 0.,              // n_hits, multiple_hit_density, width, ID
				  static_cast<geo::View_t>( fUsePlane ), // view
				  geo::PlaneID(0, 0, fUsePlane) );

      photon_v->emplace_back( photon_clus );

      const art::Ptr<recob::Cluster> cluster_ptr = makeClusterPtrPhoton( photon_v->size() - 1 );

      for (auto const& photon_hit_idx : photon_hit_v){
	size_t idx = michel.at( photon_hit_idx )._id;
	const art::Ptr<recob::Hit> hit_ptr(input_hit_h, idx);
	photon_clus_hit_assn_v->addSingle( cluster_ptr, hit_ptr);
      }

      /*
      // charge for this photon
      double Qphoton =  0;
      for (auto const& photon_hit_idx : photon_hit_v){
	size_t idx = michel.at( photon_hit_idx )._id;
	const art::Ptr<recob::Hit> hit_ptr(input_hit_h, idx);
	photon_hit_ptr_v.push_back( hit_ptr );
	Qphoton += michel[ photon_hit_idx ]._q;
      }
      */

    }// for all photons
    
  }// for all reconstructed michel electrons

  e.put(std::move(electron_v), "electron");
  e.put(std::move(elec_clus_hit_assn_v), "electron");
  e.put(std::move(photon_v), "photon");
  e.put(std::move(photon_clus_hit_assn_v), "photon");

}


std::vector< ::michel::HitPt > MichelRecoDriver::PrepareClusterHits( const std::vector<art::Ptr<recob::Hit> >& hit_v )
{
  std::vector< ::michel::HitPt > michel_cluster;
  michel_cluster.reserve( hit_v.size() );
  
  // loop over all hits and fill the cluster
  for (size_t i=0; i < hit_v.size(); i++){

    art::Ptr<recob::Hit> hit = hit_v.at( i );

    michel::HitPt hitpt( hit->Integral(),
			 hit->WireID().Wire * _w2cm,
			 hit->PeakTime() * _t2cm,
			 hit.key(),
			 hit->WireID().Plane );
    
    michel_cluster.emplace_back( hitpt );

  }// for all hits in the cluster

  return michel_cluster;
}


DEFINE_ART_MODULE(MichelRecoDriver)
